### ISSUE TITLE
beamer template: double slashes showing up in the final pdf

### ISSUE THREAD

**Issue by cknoll** [tud-cd/tud-cd#17]
In my compiled result (beamer presentation) the character sequence `//`shows up on two places: between *subtitle* and *datecity*

and in the footline between *institute* and *authors*.

I think the reasons are 

https://github.com/tud-cd/tud-cd/blob/a81253175f544fcd135e5e1c088fa68e4b70ab5d/tex/latex/tud-beamerstyle/beamerinnerthemetud.sty#L106

https://github.com/tud-cd/tud-cd/blob/a81253175f544fcd135e5e1c088fa68e4b70ab5d/tex/latex/tud-beamerstyle/beamerouterthemetud.sty#L671

Maybe they should be replaced by `\\`?

**Comment by keinstein** [comment]
The reason is that they show up in the official PowerPoint templates. So it is the intented behaviour including the surrounding spaces. The braces after \else give you a hint that the space before “//” is inteded, but it would be useless if “//” should be a line break.

BTW. Making line breaks is typographically nonsense in this situation. As you can see the 3 lines are aligned with the TUD logo, which should not be 5 lines.

See #14 for further information.

**Comment by cknoll** [comment]
Ok. Then I misunderstood the situation. Thanks for the clarification. Maybe a comment at these places would be good to prevent others from the same mistake?
